name: gdsviewer
on:
  workflow_dispatch:

jobs:
  GDSView:
      runs-on: ubuntu-latest
      steps:
      - name: GDS3D
        uses: actions/checkout@v3
        with:
          repository: mbalestrini/GDS2glTF
      
      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies

      
#      - name: Buscar repo normal
#        uses: actions/checkout@v3

#      - name: Descargar GDS
#        uses: dawidd6/action-download-artifact@v2
#        with:
#          workflow: flow.yaml
#          workflow_conclusion: success
#          name: GDS
      
#      - name: Mover gds
#        run: |
#            mkdir ${{ github.workspace }}/gds/
#            cp *.gds ${{ github.workspace }}/gds/

      - name: Buscar prerequisitos de PNG
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: librsvg2-bin pngquant
          version: tt05 # I think naming a version builds a reusable packages cache for that name.
        
      - name: Instalar Prerequisitos
        run: |
          pip install appdirs==1.4.4 cairocffi==1.6.0 CairoSVG==2.7.0 certifi==2023.5.7 cffi==1.15.1 charset-normalizer==3.1.0 click==8.1.3 cssselect2==0.7.0 defusedxml==0.7.1 gdstk==0.9.42 gitdb==4.0.10 GitPython==3.1.31 idna==3.4 importlib-resources==5.12.0 mistune==3.0.1 numpy==1.24.3 Pillow==9.5.0 pycparser==2.21 python-frontmatter==1.0.0 pytz==2023.3 PyYAML==6.0 requests==2.31.0 smmap==5.0.0 stripe==5.4.0 tinycss2==1.2.1 urllib3==2.0.3 wasmtime==9.0.0 webencodings==0.5.1 yowasp-runtime==1.22 yowasp-yosys==0.30.0.0.post538 zipp==3.15.0 pre-commit==3.4.0
          pre-commit install
                    
#      - name: Render PNG from GDS
#        shell: bash
#        run: python3 gds2png.py

#      - name: Upload gds_render (png) artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: gds_render
#          path: 'gds_render.png'
      - name: GDS3D
        uses: actions/checkout@v3
        with:
          repository: mbalestrini/GDS2glTF

      - name: Descargar GDS
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: flow.yaml
          workflow_conclusion: success
          name: GDS

      - name: gds2gltf
        shell: bash
        run: |
          ls -lh
          python -m pip install numpy gdspy triangle pygltflib
          mkdir ${{ github.workspace }}/gh-pages/
          mv ${{ github.workspace }}/gds/*.gds render.gds
          python3 gds2gltf.py render.gds
          cp render.gds.gltf gh-pages/render.gds.gltf

      - name: Generate HTML pages that redirects to viewer
        shell: bash
        run: |
          cat << EOF >> gh-pages/index.html
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="UTF-8">
              <meta http-equiv="X-UA-Compatible" content="IE=edge">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Redirecting to GDS Viewer...</title>
            </head>
            <body>
              <script>
                location.href = "https://gds-viewer.tinytapeout.com/?model=" + encodeURIComponent(location.href + '/render.gds.gltf');
              </script>
            </body>
            </html>
          EOF

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'gh-pages'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

      - name: Display preview in workflow summary
        shell: bash
        run: |
          PAGE_URL=${{ steps.deployment.outputs.page_url }}
          PAGE_URL=$(echo "$PAGE_URL" | sed -e 's/\/$//')
          cat << EOF >> $GITHUB_STEP_SUMMARY
          # 3D Viewer
          [open 3D viewer](https://gds-viewer.tinytapeout.com/?model=$PAGE_URL/tinytapeout.gds.gltf)

          # 2D Preview
          ![png]($PAGE_URL/gds_render.png)
          EOF
